name: Build phar package.
run-name: Build Zuri.phar package with build.php
on:
  push:
  workflow_dispatch:
jobs:
 build-phar:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout the repository.
       uses: actions/checkout@v4
     - name: Setup PHP
       uses: pmmp/setup-php-action@3.2.0
       with:
         php-version: 8.3
         install-path: "./bin"
         pm-version-major: 5

     - name: Install composer dependencies
        run: composer install --prefer-dist

     - name: Run php-cs-fixer (for source code)
        run: ./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --verbose

     - name: Build PHAR
       run: "run: mkdir build && composer run-script build"

     - name: Upload build artifact
       uses: actions/upload-artifact@v4
       with:
          name: LibVapmPMMP
          path: LibVapmPMMP.phar
     - name: Codespace Cleanup
       run: "rm -rf *"